site_name: ギャルゲーで学ぶ英語
site_description: 日本の美少女ゲームファンのための実践的英語教科書
site_author: Galge English Project
site_url: https://your-github-username.github.io/galge-english/

theme:
  name: material
  language: ja
  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: ダークモードに切り替え
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: ライトモードに切り替え
  font:
    text: Noto Sans JP
    code: Source Code Pro
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy

plugins:
  - search:
      lang: ja

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/galge-english
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle

copyright: Copyright &copy; 2024 Galge English Project

nav:
  - ホーム: index.md
  - 第1部 - 基礎文法編:
    - 第1章 英語の音と文字: chapter01.md
    - 第2章 基本的な文の構造: chapter02.md
    - 第3章 動詞と時制: chapter03.md
    - 第4章 名詞と冠詞: chapter04.md
    - 第5章 形容詞と副詞: chapter05.md
  - 第2部 - 日常会話編:
    - 第6章 推しキャラについて語る: chapter06.md
    - 第7章 ゲームの感想を伝える: chapter07.md
    - 第8章 フォーラムでの議論: chapter08.md
    - 第9章 レビューを書く: chapter09.md
    - 第10章 質問と回答: chapter10.md
  - 第3部 - 実践応用編:
    - 第11章 ストーリーの要約: chapter11.md
    - 第12章 キャラクター分析: chapter12.md
    - 第13章 翻訳について議論する: chapter13.md
    - 第14章 配信・実況で使う英語: chapter14.md
  - 第4部 - 上級テクニック編:
    - 第15章 ニュアンスの違い: chapter15.md
    - 第16章 ジャンル別の特徴: chapter16.md
  - 第5部 - 国際交流編:
    - 第17章 海外ファンとの交流: chapter17.md
    - 第18章 文化の違いを説明する: chapter18.md
    - 第19章 おすすめ作品を紹介する: chapter19.md
    - 第20章 コミュニティへの参加: chapter20.md
